### ISSUE TITLE
Missing build instructions

### ISSUE THREAD

**Issue by mivk** [agfline/LibAAF#1]
It would be nice to have some build instructions for people not familiar with C, who whould like to be able to use the provided tools.

All I found was in the ["Tools" section of README.md](https://github.com/agfline/LibAAF#tools) :

    To build those, just run `make` 

But that is clearly not enough:

~~~
~/src/LibAAF-master$ make
make --no-print-directory -C LibAAF
makedepend -Y LibCFB/LibCFB.c LibCFB/CFBDump.c AAFCore/AAFToText.c AAFCore/AAFDump.c AAFCore/AAFUtils.c AAFCore/AAFCore.c AAFCore/AAFClass.c AAFIface/AAFIAudioFiles.c AAFIface/ProTools.c AAFIface/AAFIface.c AAFIface/AAFIParser.c common/utils.c 2>/dev/null
make[1]: *** [Makefile:30: depend] Error 127
make: *** [Makefile:22: libAAF] Error 2
~~~

**Comment by agfline** [comment]
I think you're missing the `makedepend` tool, which is used to retrieve all the library dependencies from source code. If you're on debian, you can install it from the `xutils-dev` package by running `sudo apt-get install xutils-dev`.

Let me know if you encounter any other issue.

And as stated in the README : `LibAAF is currently a work in progress and is not production-ready yet.`
