### ISSUE TITLE
Unrelated functions in libAAF

### ISSUE THREAD

**Issue by x42** [agfline/LibAAF#11]
libAAF is a library to handle AAF files it should not concern itself with anything else.

Please consider removing unrelated functions from the library that are not directly related to AAF.
e.g. aafi_enable_windows_VT100_output.

**Comment by agfline** [comment]
I understand and I agree. However, AAF being such a complex file structure, the only way I found for debugging was to put colors and UTF-8 symbols to print a tree of objects and classes to stdout. No problem for that on linux, but windows requires that VT100 output trigger...
Maybe this function could be left as a helper function for development only ?

**Comment by umlaeute** [comment]
i agree with @x42 that this shouldn't be part of the public API.

afaict, this function is used by the tools `AAFExtract` and `AAFInfo`, so why not put it into a *private* header  (`tools/AAFTools_utils.h`) that is included by these two tools and be done with it?

**Comment by agfline** [comment]
Yes, but at some point it will be problematic if users request support with those uncolored debug traces. But maybe that's another problem.
