### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by dvzrv** [agfline/LibAAF#13]
Hi! :wave: 
As I'm currently looking into packaging this library to be able to upgrade ardour, it would be great if you could create a new release soon.

The import into ardour's sources happened at 85 commits past the 0.1 release (which includes quite a lot of fixes):
https://github.com/Ardour/ardour/commit/7593551e490f8ecf60f65f20b84654cf1dfef3cf

I am currently blocked from even packaging 0.1 by #12, however after that is resolved it would be very good to create a release, as currently this library blocks me from upgrading ardour to 8.2.

**Comment by agfline** [comment]
I first have to fix an issue https://github.com/agfline/LibAAF/issues/7#issuecomment-1854104404 then I'll do the release.
You need a source release right ?

**Comment by agfline** [comment]
I just created https://github.com/agfline/LibAAF/releases/tag/v0.1-85-g3e4c2cd which matches the exact version inside Ardour's 8.2 source tree since https://github.com/Ardour/ardour/commit/7593551e490f8ecf60f65f20b84654cf1dfef3cf
