### ISSUE TITLE
Fails to build with " error: 'aafiAudioClip' has no member named 'subClipName' "

### ISSUE THREAD

**Issue by benalb** [agfline/LibAAF#25]
Cloned the repo, followed the instructions to build, but failed with this:

`[ 73%] Building C object CMakeFiles/AAFInfo.dir/tools/AAFInfo.c.o
/home/benalb/tmp/LibAAF/tools/AAFInfo.c: In function 'main':
/home/benalb/tmp/LibAAF/tools/AAFInfo.c:775:59: error: 'aafiAudioClip' has no member named 'subClipName'
  775 |                                                 (audioClip->subClipName) ? "  ClipName: \"" : "",
      |                                                           ^~
/home/benalb/tmp/LibAAF/tools/AAFInfo.c:776:59: error: 'aafiAudioClip' has no member named 'subClipName'
  776 |                                                 (audioClip->subClipName) ? audioClip->subClipName : L"",
      |                                                           ^~
/home/benalb/tmp/LibAAF/tools/AAFInfo.c:776:85: error: 'aafiAudioClip' has no member named 'subClipName'
  776 |                                                 (audioClip->subClipName) ? audioClip->subClipName : L"",
      |                                                                                     ^~
/home/benalb/tmp/LibAAF/tools/AAFInfo.c:777:59: error: 'aafiAudioClip' has no member named 'subClipName'
  777 |                                                 (audioClip->subClipName) ? "\" " : "" );
      |                                                           ^~
make[2]: *** [CMakeFiles/AAFInfo.dir/build.make:76: CMakeFiles/AAFInfo.dir/tools/AAFInfo.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:116: CMakeFiles/AAFInfo.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

`

**Comment by agfline** [comment]
Looks like master branch is broken... sorry about that.
I'm working on a major update (which will also fix that issue), I'll push it in a couple days. In the meantime, you can download the [latest release](https://github.com/agfline/LibAAF/releases/tag/v0.5).
