### ISSUE TITLE
Licensing AGPL + Ardour

### ISSUE THREAD

**Issue by x42** [agfline/LibAAF#3]
Is there a reason why you have picked AGPL?
For code to be used with Ardour we have so far avoided any AGPL code and libraries.

Seeing as this is a library, LGPL would be much better suited to begin with. Thanks for considering.

**Comment by agfline** [comment]
No particular reason, just want to stick to free software. 
Is LGPLv3 ok for Ardour ?

**Comment by x42** [comment]
PS. to elaborate
https://en.wikipedia.org/wiki/Affero_General_Public_License#Compatibility_with_the_GPL

The "application service provider" loophole is not really an issue with Ardour. Although in theory someone could use your library and run a web-service without ever contributing their changes back to you. But more realistically you do not want contributions from those persons in the first place, nor spend time suing them... YMMV.

**Comment by agfline** [comment]
Ok, after some reading I will go with GPL v2 for the library.
